config/routes.rb
Rails.application.routes.draw do
  root 'messages#index'
  resources :messages do
    member do
      get :decrypt
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  before_save :encrypt
  before_save :uuidgen

# gracias -> https://www.it-swarm-es.com/es/ruby/como-reemplazar-los-caracteres-en-una-cadena/828570107/

  def encrypt
    replacements = {
      'e' => '_/¯¯-__',
      'E' => '_/¯¯_',
      'a' => '__/_//¯¯¯',
      'A' => '_//¯¯',
      'o' => '__-//¯¯-',
      'O' => '_¯¯-',
      's' => '-//-_¯¯',
      'S' => '-//',
      'r' => '__//¯_/',
      'R' => '__//¯_/',
      'n' => '¯//_-/¯¯¯',
      'N' => '¯-/¯¯¯ ',
      's' => '_/-/¯¯',
      'S' => '_/-/¯¯',
      'r' => '__//¯_/',
      'R' => '_¯_/',
      'n' => '¯//_-/',
      'N' => '¯//',
      'i' => '_/-/¯¯',
      'I' => '_/¯¯',
      'd' => '/¯_/¯__',
      'D' => '/¯_____',
      'l' => '/_/ _//',
      'L' => '/ ___//',
      'c' => '¯¯/__-',
      'C' => '__-',
      't' => '-/__/¯',
      'T' => '-__',
      'u' => '___///¯',
      'U' => '__¯',
      'm' => '/_',
      'M' => '/_--_-',
      'p' => '///_-',
      'P' => '---  -',
      'b' => '__//¯',
      'B' => '__ /--',
      'g' => '/_/_',
      'G' => '/___/_',
      'v' => '/¯/¯-__',
      'V' => '/¯¯¯',
      'y' => '_//',
      'Y' => '_/___',
      'q' => '--_//',
      'Q' => '/',
      'h' => '/¯-¯/',
      'H' => '¯-¯',
      'f' => '_¯/__',
      'F' => '_-¯/_',
      'z' => '//_/__',
      'F' => '/_/',
      'j' => '/',
      'J' => '/--/_',
      'ñ' => '//-',
      'Ñ' => '//-',
      'x' => '/¯¯--_/',
      'X' => '/-¯¯/',
      'k' => '-----/',
      'K' => '--/\\',
      'w' => '---',
      'W' => '--\-',
      'á' => '__/-----',
      'é' => '_-¯-',
      'í' => '_---¯-',
      'ó' => '_--/¯-',
      'ú' => '-/¯-\\',
      'ü' => '\\_--/',
      '#' => '-_////',
      '¿' => '-----_----',
      '?' => '--_///-/¯--',
      '"' => '_\\\\__',
      '!' => '_.-¯-.',
      '¡' => '_/¯¯¯¯¯¯¯¯',
      '&' => '...',
      '(' => '----',
      ')' => '____',
      '*' => '-/-',
      '+' => '-//-',
      '~' => '-',
      '@' => '/--',
      '0' => '-',
      '1' => '--.',
      '2' => '--.-',
      '3' => '.--.',
      '4' => '.-/',
      '5' => '\/..',
      '6' => '.-/',
      '7' => '¯¯\ ',
      '8' => '¯- ',
      '9' => '-_-¯-',
      '$' => '-', }.
  tap { |h| h.default_proc = ->(h,k) { k } }
  self.translated_body = "#{body}".gsub(/./, replacements)
  end
  def uuidgen
    self.uuid = SecureRandom.hex 3
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[show edit update destroy decrypt]

  # GET /messages or /messages.json
  def index
    @q = Message.ransack(params[:q])
    @messages = @q.result
  end

  # GET /messages/1 or /messages/1.json
  def show
  end

  def decrypt
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages or /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: "Message was successfully created." }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: "Message was successfully updated." }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1 or /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: "Message was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:body, :translated_body, :uuid, :author, :receiver)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Txt2txt en T.R.A.T.E.N by librenauta</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with(model: message) do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="row d-flex align-item-center justify-content-center">
  <div class="col-md-6 mt-1">
    <div>
        <h1>T2T on T.R.A.T.E.N</h1>
        <p>by <i class="li">@librenauta</i></p>
    </div>
    <div>
        <h3>Escribí un mensaje y convertilo en un: /¯-¯/__-//¯¯-/_/</h3>
        <p>Compartí el {ID} a quien quieras que lo lea para descubrirlo en <i class="liquen">t2t.copiona.com</i></p>
    </div>
    <div class="form flex-column">
      <div class="field d-flex flex-column">
        <%= form.label :Autora %>
        <%= form.text_field :author %>
      </div>

      <div class="field mt-2 d-flex flex-column">
        <%= form.label :Receptora %>
        <%= form.text_field :receiver %>
      </div>
      <div class="field mt-2 d-flex flex-column">
        <%= form.label :Texto %>
        <%= form.text_area :body %>
      </div>

      <div class="actions row no-gutters flex-column mt-5 d-flex align-item-center justify-content-center">
        <%= form.submit %>
        <div class="mt-4 broder border-1 p-2 d-flex align-item-center justify-content-center">
          <%= link_to '-> Buscar mensaje con #hash', messages_path %>
        </div>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/messages/_search_form.html.erb
<div class="row m-3 d-flex flex-column align-items-center justify-content-center">
  <%= search_form_for @q do |f| %>
    <%= f.label :uuid_cont %>
    <%= f.search_field :uuid_cont %>

    <%= f.submit %>
  <% end %>
</div>

app/views/messages/decrypt.html.erb
<div class="row d-flex align-item-center justify-content-center mt-5">
  <div class="col-md-6 mt-5">
    <div>
        <h1>T2T on T.R.A.T.E.N</h1>
        <p>by <i class="li">@librenauta</i></p>
    </div>
    <h2>Mensaje traducido</h2>
    <div class="f-3">
        <%= @message.body %>
    </div>


<div class="field mt-2 d-flex flex-column">
  <strong>{ID}: </strong>
  <%= @message.uuid %>
</div>

<div class="field mt-2 d-flex flex-column">
  <strong>De: </strong>
  <%= @message.author %>
</div>

<div class="field mt-2 d-flex flex-column">
  <strong>Para: </strong>
  <%= @message.receiver %>
</div>
<div class="mt-3 li-btn d-flex align-item-center justify-content-center ">
  <%= link_to 'Back', new_message_path %>
</div>

  </div>
</div>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<div class="row flex-column align-items-center justify-content-center">
  <h1>txt2txt en TRATEN</h1>

  <p>Acá ingresando un UUID ej: '893223' de 6 digitos podrás descubrir un mensaje</p>
</div>
<div class="row align-items-center justify-content-center">
  <%= render 'search_form' %>
  <div class="">
    <%= link_to 'New Message', new_message_path %>
  </div>
</div>
<% @messages.each do |message| %>
<div class="row border-1 d-flex flex-column align-items-center justify-content-center">
  <div class="col-md-6">
    <p class="salmon">Mensaje</p>
    <%= message.translated_body %>
  </div>
  <div class="">
    <p class="salmon">{ID} #<%= message.uuid %></p>
  </div>
  <div class="d-flex align-items-center justify-content-center">
    <p class="salmon">~De: </p>
    <%= message.author %>
  </div>
  <div class="d-flex align-items-center justify-content-center">
    <p class="salmon">~Para: </p>
    <%= message.receiver %>
  </div>
  <div class="">
    <%= link_to 'Back', new_message_path %>
    <%= link_to 'Decrypt', decrypt_message_path(message) %>
  </div>
<hr aria-hidden="true" class="border-top border-black border-1 mb-2 w-50"/>
</div>
<% end %>

app/views/messages/new.html.erb
<%= render 'form', message: @message %>

app/views/messages/show.html.erb
<div class="row flex-column align-items-center justify-content-center mb-3">
  <div class="d-flex flex-column">
      <h1>T2T on T.R.A.T.E.N</h1>
      <p>by <i class="li">@librenauta</i></p>
  </div>
  <div class="row flex-column align-items-center justify-content-center">
    <div class="col-md-6">
      <strong class="ml-3 salmon">Mensaje:</strong>
        <div class="m-3">
        <%= @message.translated_body %>
        </div>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <p>
        <strong class="salmon">{ID}:</strong>
        #<%= @message.uuid %>
      </p>

      <p>
        <strong class="salmon">Autora:</strong>
        <%= @message.author %>
      </p>

      <p>
        <strong class="salmon">Receptora:</strong>
        <%= @message.receiver %>
      </p>
      <p>traducilo en <i>t2t.copiona.com</i></p>
      <%= link_to 'Atrás', new_message_path %>
      <a href="#" onclick="window.print();">Imprimir</a>
    </div>
  </div>
</div>